name: nc_flutter_hello
description: A new Hello Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/menu_icon.png
    - images/1.5x/menu_icon.png
    - images/2.0x/menu_icon.png
    - images/3.0x/menu_icon.png
    - images/search_icon.png
    - images/1.5x/search_icon.png
    - images/2.0x/search_icon.png
    - images/3.0x/search_icon.png
    - images/notify_icon.png
    - images/1.5x/notify_icon.png
    - images/2.0x/notify_icon.png
    - images/3.0x/notify_icon.png
    - images/banner.png
    - images/1.5x/banner.png
    - images/2.0x/banner.png
    - images/3.0x/banner.png
    - images/search_bar_icon.png
    - images/1.5x/search_bar_icon.png
    - images/2.0x/search_bar_icon.png
    - images/3.0x/search_bar_icon.png
    - images/search_bar_qr.png
    - images/1.5x/search_bar_qr.png
    - images/2.0x/search_bar_qr.png
    - images/3.0x/search_bar_qr.png
    - images/item_bg.png
    - images/1.5x/item_bg.png
    - images/2.0x/item_bg.png
    - images/3.0x/item_bg.png
    - images/computer_icon.png
    - images/1.5x/computer_icon.png
    - images/2.0x/computer_icon.png
    - images/3.0x/computer_icon.png
    - images/more_icon.png
    - images/1.5x/more_icon.png
    - images/2.0x/more_icon.png
    - images/3.0x/more_icon.png
    - images/back_icon.png
    - images/1.5x/back_icon.png
    - images/2.0x/back_icon.png
    - images/3.0x/back_icon.png
    - images/indicator_connect.png
    - images/1.5x/indicator_connect.png
    - images/2.0x/indicator_connect.png
    - images/3.0x/indicator_connect.png
    - images/bargain_booking.png
    - images/3.0x/bargain_booking.png
    - images/how_icon_1.png
    - images/3.0x/how_icon_1.png
    - images/how_icon_2.png
    - images/3.0x/how_icon_2.png
    - images/instant_booking.png
    - images/3.0x/instant_booking.png
    - images/item_small.png
    - images/3.0x/item_small.png
    - images/shoe_pic.png
    - images/3.0x/shoe_pic.png
    - images/when_icon_2.png
    - images/3.0x/when_icon_2.png
    - images/where_icon_2.png
    - images/3.0x/where_icon_2.png
    - images/which_icon_1.png
    - images/3.0x/which_icon_1.png
    - images/which_icon_2.png
    - images/3.0x/which_icon_2.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
